# Generated by Django 4.2.15 on 2025-02-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id'], 'verbose_name_plural': '01. Carts'},
        ),
    ]
